from flask import Flask
from flask_cors import CORS


app = Flask(__name__)
cors = CORS(app)


@app.route("/<contentid>")
def example(contentid):
    # the schema will be very important to get right
    # should ids and parentids be autogenerated?
    return {
        "version": 1,
        "contentid": contentid,
        "id": 0,
        "parentid": -1,
        "metadata": {},
        "content": f"""
#Main Topic

Test
---

[Sub-topic 1](/{contentid}/1)
[Sub-topic 2](/{contentid}/2)
""",
        "children": [
            {
                "id": 1,
                "parentid": 0,
                "metadata": {},
                "content": f"""
#Sub-topic 1

> so cool
`what about this?`

[Sub-sub 3](/{contentid}/3)
                """,
                "children": [
                    {
                        "id": 3,
                        "parentid": 1,
                        "metadata": {},
                        "content": """#1->3""",
                        "children": [],
                    }
                ],
            },
            {
                "id": 2,
                "parentid": 0,
                "metadata": {},
                "content": """#Sub-topic 2""",
                "children": [],
            },
        ],
    }
