import { css } from "lit";

export const animationStyles = css`
  .slide-right {
    -webkit-animation: slide-right 0.2s cubic-bezier(0.25, 0.46, 0.45, 0.94)
      both;
    animation: slide-right 0.2s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
  }

  .slide-left {
    -webkit-animation: slide-left 0.2s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
    animation: slide-left 0.2s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
  }

  /* ----------------------------------------------
 * Generated by Animista on 2023-5-31 17:52:25
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

  /**
 * ----------------------------------------
 * animation slide-right
 * ----------------------------------------
 */
  @-webkit-keyframes slide-right {
    0% {
      -webkit-transform: translateX(calc(-1*var(--menu-width, 200px)));
      transform: translateX(calc(-1*var(--menu-width, 200px)));
    }
    100% {
      -webkit-transform: translateX(0px);
      transform: translateX(0px);
    }
  }
  @keyframes slide-right {
    0% {
      -webkit-transform: translateX(calc(-1*var(--menu-width, 200px)));
      transform: translateX(calc(-1*var(--menu-width, 200px)));
    }
    100% {
      -webkit-transform: translateX(0px);
      transform: translateX(0px);
    }
  }

  /* ----------------------------------------------
 * Generated by Animista on 2023-5-31 18:4:44
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

  /**
 * ----------------------------------------
 * animation slide-left
 * ----------------------------------------
 */
  @-webkit-keyframes slide-left {
    0% {
      -webkit-transform: translateX(0);
      transform: translateX(0);
    }
    100% {
      -webkit-transform: translateX(calc(-1*var(--menu-width, 200px)));
      transform: translateX(calc(-1*var(--menu-width, 200px)));
    }
  }
  @keyframes slide-left {
    0% {
      -webkit-transform: translateX(0);
      transform: translateX(0);
    }
    100% {
      -webkit-transform: translateX(calc(-1*var(--menu-width, 200px)));
      transform: translateX(calc(-1*var(--menu-width, 200px)));
    }
  }
`;
